services:
  backend:
    build:
      context: .
      dockerfile: ./_docker/backend/Dockerfile
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    tty: true
    working_dir: /var/www
    volumes:
      - .:/var/www
      - ./_docker/backend/php.ini:/usr/local/etc/php/php.ini
    depends_on:
      - db_cicd

  nginx:
    image: nginx:alpine
    restart: unless-stopped
    tty: true
    ports:
      - "8480:80" # http://localhost:8480/
    volumes:
      - .:/var/www
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    depends_on:
      - backend

  db_cicd:
    image: mysql:8.4.0
    restart: unless-stopped
    tty: true
    ports:
      - 8406:3306
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    environment:
      MYSQL_DATABASE: laravel__cicd
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'user'
    volumes:
      - ./tmp/db_cicd:/var/lib/mysql
      - ./_docker/mysql/my.cnf:/etc/mysql/my.cnf
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping" ]

  node:
    build:
      context: .
      dockerfile: ./_docker/nodejs/Dockerfile
    tty: true
    ports:
      - "8473:5173" # "8473:5173"
    working_dir: /var/www
    volumes:
      - .:/var/www
